package parserecipe

var corpusIngredients = []string{" can cream of chicken soup ",
	" cream of mushroom soup ",
	" graham cracker crumbs ",
	" salt and black pepper ",
	" heavy whipping cream ",
	" vegetable shortening ",
	" worcestershire sauce ",
	" apple cider vinegar ",
	" confectioners sugar ",
	" white wine vinegar ",
	" black peppercorns ",
	" cream of mushroom ",
	" green bell pepper ",
	" italian seasoning ",
	" mozzarella cheese ",
	" pumpkin pie spice ",
	" red pepper flakes ",
	" vanilla ice cream ",
	" artichoke hearts ",
	" balsamic vinegar ",
	" broccoli florets ",
	" butternut squash ",
	" hot pepper sauce ",
	" jalapeno chilies ",
	" red wine vinegar ",
	" american cheese ",
	" cherry tomatoes ",
	" chicken breasts ",
	" cilantro leaves ",
	" cream of tartar ",
	" evaporated milk ",
	" flour tortillas ",
	" graham crackers ",
	" lasagna noodles ",
	" mzarella cheese ",
	" parmesan cheese ",
	" pineapple juice ",
	" red bell pepper ",
	" salt and pepper ",
	" vegetable broth ",
	" vegetable stock ",
	" water chestnuts ",
	" yellow cake mix ",
	" yellow cornmeal ",
	" almond extract ",
	" barbecue sauce ",
	" cayenne pepper ",
	" cheddar cheese ",
	" chicken breast ",
	" chicken thighs ",
	" corn tortillas ",
	" cottage cheese ",
	" dark chocolate ",
	" dry white wine ",
	" parsley flakes ",
	" parsley leaves ",
	" powdered sugar ",
	" ricotta cheese ",
	" seasoning salt ",
	" smoked paprika ",
	" sweet potatoes ",
	" teriyaki sauce ",
	" whipping cream ",
	" baking powder ",
	" chicken broth ",
	" chicken stock ",
	" cider vinegar ",
	" cooking spray ",
	" dijon mustard ",
	" garlic powder ",
	" green chilies ",
	" green peppers ",
	" half and half ",
	" peanut butter ",
	" plum tomatoes ",
	" potato starch ",
	" tabasco sauce ",
	" vegetable oil ",
	" whipped cream ",
	" white vinegar ",
	" almond flour ",
	" baby spinach ",
	" basil leaves ",
	" black olives ",
	" black pepper ",
	" bread crumbs ",
	" chicken soup ",
	" chili powder ",
	" coconut milk ",
	" corn kernels ",
	" cream cheese ",
	" curry powder ",
	" dry red wine ",
	" garam masala ",
	" green onions ",
	" green pepper ",
	" kidney beans ",
	" marshmallows ",
	" onion powder ",
	" orange juice ",
	" purple onion ",
	" rice vinegar ",
	" sesame seeds ",
	" strawberries ",
	" swiss cheese ",
	" thyme leaves ",
	" tomato juice ",
	" tomato paste ",
	" tomato sauce ",
	" walnut flour ",
	" white pepper ",
	" yellow onion ",
	" almond meal ",
	" almond milk ",
	" apple juice ",
	" baking soda ",
	" bell pepper ",
	" black beans ",
	" blue cheese ",
	" blueberries ",
	" bread flour ",
	" breadcrumbs ",
	" brown sugar ",
	" cauliflower ",
	" celery seed ",
	" chili sauce ",
	" coconut oil ",
	" cooking oil ",
	" corn starch ",
	" cranberries ",
	" dry mustard ",
	" egg noodles ",
	" feta cheese ",
	" garlic salt ",
	" goat cheese ",
	" green beans ",
	" green onion ",
	" heavy cream ",
	" horseradish ",
	" lemon juice ",
	" maple syrup ",
	" mint leaves ",
	" orange peel ",
	" raspberries ",
	" red peppers ",
	" rice noodle ",
	" sweet onion ",
	" tomato soup ",
	" white onion ",
	" applesauce ",
	" bay leaves ",
	" beef broth ",
	" beef stock ",
	" brown rice ",
	" buttermilk ",
	" canola oil ",
	" corn flour ",
	" corn syrup ",
	" cornstarch ",
	" cumin seed ",
	" dry sherry ",
	" fish sauce ",
	" lemon peel ",
	" lemon rind ",
	" lime juice ",
	" matzo meal ",
	" mayonnaise ",
	" peanut oil ",
	" peppermint ",
	" prosciutto ",
	" red pepper ",
	" rice flour ",
	" sesame oil ",
	" shortening ",
	" sour cream ",
	" white rice ",
	" white wine ",
	" asparagus ",
	" chickpeas ",
	" chocolate ",
	" cool whip ",
	" coriander ",
	" dill weed ",
	" hamburger ",
	" hazelnuts ",
	" hot sauce ",
	" margarine ",
	" mushrooms ",
	" oat flour ",
	" olive oil ",
	" pie crust ",
	" pie shell ",
	" pine nuts ",
	" pineapple ",
	" red onion ",
	" salad oil ",
	" scallions ",
	" skim milk ",
	" soy sauce ",
	" spaghetti ",
	" allspice ",
	" bay leaf ",
	" broccoli ",
	" cardamom ",
	" cherries ",
	" cilantro ",
	" cinnamon ",
	" cornmeal ",
	" crabmeat ",
	" cucumber ",
	" dressing ",
	" eggplant ",
	" marjoram ",
	" molasses ",
	" potatoes ",
	" red wine ",
	" rosemary ",
	" semolina ",
	" shallots ",
	" tarragon ",
	" tomatoes ",
	" turmeric ",
	" zucchini ",
	" almonds ",
	" arugula ",
	" avocado ",
	" bananas ",
	" cabbage ",
	" carrots ",
	" cashews ",
	" cayenne ",
	" chicken ",
	" coconut ",
	" gelatin ",
	" ketchup ",
	" lettuce ",
	" mustard ",
	" oatmeal ",
	" oranges ",
	" oregano ",
	" paprika ",
	" parsley ",
	" peaches ",
	" peanuts ",
	" pumpkin ",
	" raisins ",
	" sausage ",
	" shallot ",
	" spinach ",
	" vanilla ",
	" vinegar ",
	" walnuts ",
	" apples ",
	" banana ",
	" brandy ",
	" butter ",
	" capers ",
	" carrot ",
	" catsup ",
	" celery ",
	" cheese ",
	" chives ",
	" coffee ",
	" fennel ",
	" garlic ",
	" ginger ",
	" lemons ",
	" nutmeg ",
	" olives ",
	" onions ",
	" orange ",
	" pecans ",
	" pepper ",
	" potato ",
	" quinoa ",
	" salmon ",
	" shrimp ",
	" tomato ",
	" turkey ",
	" yogurt ",
	" apple ",
	" bacon ",
	" banana ",
	" basil ",
	" beans ",
	" beets ",
	" bread ",
	" chile ",
	" clove ",
	" cocoa ",
	" cream ",
	" cumin ",
	" dates ",
	" flour ",
	" fruit ",
	" honey ",
	" leeks ",
	" lemon ",
	" mango ",
	" onion ",
	" pasta ",
	" pears ",
	" salad ",
	" salsa ",
	" sauce ",
	" spray ",
	" steak ",
	" sugar ",
	" thyme ",
	" vodka ",
	" water ",
	" yeast ",
	" beef ",
	" beer ",
	" corn ",
	" dill ",
	" eggs ",
	" flax ",
	" kale ",
	" lamb ",
	" lime ",
	" milk ",
	" mint ",
	" nuts ",
	" oats ",
	" peas ",
	" pork ",
	" rice ",
	" sage ",
	" salt ",
	" soda ",
	" thru ",
	" tofu ",
	" tuna ",
	" ham ",
	" ice ",
	" oil "}
var corpusMeasures = []string{" tablespoons ",
	" milliliter ",
	" tablespoon ",
	" teaspoons ",
	" teaspoon ",
	" canned ",
	" ounces ",
	" pounds ",
	" quarts ",
	" grams ",
	" ounce ",
	" pints ",
	" pound ",
	" quart ",
	" tbsps ",
	" cans ",
	" cups ",
	" gram ",
	" pint ",
	" tbsp ",
	" tsps ",
	" can ",
	" cup ",
	" tbl ",
	" tsp ",
	" ml ",
	" oz ",
	" c ",
	" g "}
var corpusNumbers = []string{" 1/2 ",
	" 1/3 ",
	" 1/4 ",
	" 1/5 ",
	" 1/6 ",
	" 1/7 ",
	" 1/8 ",
	" 2/3 ",
	" 2/5 ",
	" 2/7 ",
	" 3/4 ",
	" 3/8 ",
	" 4/5 ",
	" 5/8 ",
	" 7/8 ",
	" 1 ",
	" 2 ",
	" 3 ",
	" 4 ",
	" 5 ",
	" 6 ",
	" 7 ",
	" 8 ",
	" 9 ",
	" 10 ",
	" 11 ",
	" 12 ",
	" 13 ",
	" 14 ",
	" 15 ",
	" 16 ",
	" 17 ",
	" 18 ",
	" 19 ",
	" 20 ",
	" ⅔ ",
	" ½ ",
	" ⅛ ",
	" ⅜ ",
	" ⅝ ",
	" ⅞ ",
	" ¼ ",
	" ¾ ",
	" ⅓ "}
var corpusDirections = []string{"1",
	"10",
	"15",
	"2",
	"25",
	"375",
	"6",
	"8",
	"9x13",
	"a",
	"about",
	"achieve",
	"add",
	"additional",
	"an",
	"and",
	"arrange",
	"assemble",
	"bake",
	"baking",
	"basil",
	"beef",
	"before",
	"boil",
	"boiling",
	"bottom",
	"bowl",
	"bring",
	"brown",
	"browned",
	"cheese",
	"coconut",
	"cold",
	"color",
	"combine",
	"cook",
	"cooking",
	"cool",
	"cover",
	"covered",
	"crushed",
	"cup",
	"cups",
	"degrees",
	"dish",
	"distributed",
	"does",
	"drain",
	"dutch",
	"eggs",
	"either",
	"even",
	"evenly",
	"f",
	"fennel",
	"foil",
	"for",
	"from",
	"garlic",
	"ground",
	"half",
	"heat",
	"hours",
	"in",
	"inch",
	"into",
	"italian",
	"large",
	"lasagna",
	"layers",
	"lengthwise",
	"lightly",
	"make",
	"meat",
	"medium",
	"minutes",
	"mix",
	"mixing",
	"mixture",
	"mozzarella",
	"noodles",
	"not",
	"nuts",
	"oats",
	"occasionally",
	"of",
	"onion",
	"or",
	"oven",
	"over",
	"pans",
	"parmesan",
	"parsley",
	"paste",
	"pepper",
	"pot",
	"preheat",
	"preheated",
	"prevent",
	"raisins",
	"remaining",
	"remove",
	"repeat",
	"ricotta",
	"rinse",
	"salt",
	"salted",
	"sauce",
	"sausage",
	"season",
	"seasoning",
	"seeds",
	"serving",
	"sheet",
	"simmer",
	"slices",
	"spoon",
	"spray",
	"spread",
	"sprinkle",
	"sticking",
	"stir",
	"stirring",
	"sugar",
	"sure",
	"tablespoon",
	"tablespoons",
	"teaspoon",
	"the",
	"third",
	"to",
	"tomato",
	"tomatoes",
	"top",
	"touch",
	"transfer",
	"until",
	"water",
	"well",
	"with",
	"¼",
	"½"}

type fractionNumber struct {
	fractionString string
	value          float64
}

var corpusFractionNumberMap = map[string]fractionNumber{
	"¼": {"1/4", 0.2500000000},
	"½": {"1/2", 0.5000000000},
	"¾": {"3/4", 0.7500000000},
	"⅓": {"1/3", 0.3333333333},
	"⅔": {"2/3", 0.6666666667},
	"⅛": {"1/8", 0.1250000000},
	"⅜": {"3/8", 0.3750000000},
	"⅝": {"5/8", 0.6250000000},
	"⅞": {"7/8", 0.8750000000},
}

var corpusMeasuresMap = map[string]string{
	"c":           "cup",
	"can":         "can",
	"canned":      "can",
	"cans":        "can",
	"cup":         "cup",
	"cups":        "cup",
	"g":           "gram",
	"gram":        "gram",
	"grams":       "gram",
	"milliliter":  "milliliter",
	"ml":          "milliliter",
	"ounce":       "ounce",
	"ounces":      "ounce",
	"oz":          "ounce",
	"pint":        "pint",
	"pints":       "pint",
	"pound":       "pound",
	"pounds":      "pound",
	"quart":       "quart",
	"quarts":      "quart",
	"tablespoon":  "tbl",
	"tablespoons": "tbl",
	"tbl":         "tbl",
	"tbsp":        "tbl",
	"tbsps":       "tbl",
	"teaspoon":    "tsp",
	"teaspoons":   "tsp",
	"tsp":         "tsp",
	"tsps":        "tsp",
}
